version: '3.1'

services:

  pet-hotel-database:
    image: postgres:alpine3.16
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app-user
      POSTGRES_DB: pet_hotel
    ports:
      - "5432:5432"