spring:
  datasource:
    username: ${SPRING_DATA_SOURCE_USERNAME:app-user} 
    password: ${SPRING_DATA_SOURCE_USERNAME:password} 
    url: ${SPRING_DATA_SOURCE_URL:jdbc:postgresql://localhost:5432/pet_hotel}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
